version: '3'

services:

  mariadb:
    image: mariadb
    container_name: db_mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_USER=home_work
      - MYSQL_DATABASE=home_work
      - MYSQL_PASSWORD=12345
    ports:
      - 9826:3306
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: db_phpmyadmin
    environment:
      - PMA_HOST=db_phpmyadmin
      - UPLOAD_LIMIT= 5242880000
    ports:
      - 9825:80
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379

volumes:
  mariadb_data:
  postgres_data:
